name: Î©.8 AI Threat Analyzer
on:
Â  workflow_run:
Â  Â  workflows: ["CI - Build / Lint / Test / Security Scan (Î© Clean)"]
Â  Â  types: [completed]
jobs:
Â  ai-security:
Â  Â  runs-on: ubuntu-latest
Â  Â  steps:
Â  Â  Â  - uses: actions/checkout@v4
Â  Â  Â  - name: Analyze Bandit Report
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  cat bandit-report.json | tail -n 200 > security_summary.txt || true
Â  Â  Â  - name: Generate Security Patch via GPT
Â  Â  Â  Â  env:
Â  Â  Â  Â  Â  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  curl https://api.openai.com/v1/chat/completions \
Â  Â  Â  Â  Â  Â  -H "Authorization: Bearer $OPENAI_API_KEY" \
Â  Â  Â  Â  Â  Â  -H "Content-Type: application/json" \
Â  Â  Â  Â  Â  Â  -d '{
Â  Â  Â  Â  Â  Â  Â  "model": "gpt-5",
Â  Â  Â  Â  Â  Â  Â  "messages": [
Â  Â  Â  Â  Â  Â  Â  Â  {"role":"system","content":"Analyze security vulnerabilities and propose code patch"},
Â  Â  Â  Â  Â  Â  Â  Â  {"role":"user","content":"'"$(cat security_summary.txt | jq -Rs .)"'"}
Â  Â  Â  Â  Â  Â  Â  ]
Â  Â  Â  Â  Â  Â  }' | jq -r '.choices[0].message.content' > fix_security.diff
Â  Â  Â  - name: Apply and PR
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  if grep -q "diff --git" fix_security.diff; then
Â  Â  Â  Â  Â  Â  git apply fix_security.diff || true
Â  Â  Â  Â  Â  Â  git checkout -b fix/security-auto-$(date +%s)
Â  Â  Â  Â  Â  Â  git add .
Â  Â  Â  Â  Â  Â  git commit -m "ðŸ”’ fix: AI Security Patch"
Â  Â  Â  Â  Â  Â  git push -u origin HEAD
Â  Â  Â  Â  Â  Â  gh pr create --title "AI Security Patch (Î©.8)" --body "Auto-generated security patch from Î©.8 analyzer."
Â  Â  Â  Â  Â  else
Â  Â  Â  Â  Â  Â  echo "No actionable security patch generated."
Â  Â  Â  Â  Â  fi
