name: Î©.6 AI Auto-Fix Pipeline
on:
Â  workflow_run:
Â  Â  workflows: ["CI - Build / Lint / Test / Security Scan (Î© Clean)"]
Â  Â  types: [completed]
permissions:
Â  contents: write
Â  pull-requests: write
jobs:
Â  ai-auto-fix:
Â  Â  runs-on: ubuntu-latest
Â  Â  if: ${{ github.event.workflow_run.conclusion == 'failure' }}
Â  Â  steps:
Â  Â  Â  - name: Checkout Repository
Â  Â  Â  Â  uses: actions/checkout@v4
Â  Â  Â  - name: Retrieve Failed Logs
Â  Â  Â  Â  uses: actions/download-artifact@v4
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  path: ./ci-logs
Â  Â  Â  - name: Summarize CI Failure
Â  Â  Â  Â  id: summarize
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  LOGFILE=$(find ./ci-logs -type f | head -1)
Â  Â  Â  Â  Â  cat "$LOGFILE" | tail -n 100 > failure_summary.txt
Â  Â  Â  - name: Run GPT-5 Auto-Fix Suggestion
Â  Â  Â  Â  id: gptfix
Â  Â  Â  Â  env:
Â  Â  Â  Â  Â  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  curl https://api.openai.com/v1/chat/completions \
Â  Â  Â  Â  Â  Â  -H "Authorization: Bearer $OPENAI_API_KEY" \
Â  Â  Â  Â  Â  Â  -H "Content-Type: application/json" \
Â  Â  Â  Â  Â  Â  -d '{
Â  Â  Â  Â  Â  Â  Â  "model": "gpt-5",
Â  Â  Â  Â  Â  Â  Â  "messages": [
Â  Â  Â  Â  Â  Â  Â  Â  {"role": "system", "content": "You are an AI DevOps Engineer for ZeaZDev. Read CI logs and propose a minimal safe code fix."},
Â  Â  Â  Â  Â  Â  Â  Â  {"role": "user", "content": "'"$(cat failure_summary.txt | jq -Rs .)"'"}
Â  Â  Â  Â  Â  Â  Â  ]
Â  Â  Â  Â  Â  Â  }' | jq -r '.choices[0].message.content' > ai_fix.patch
Â  Â  Â  - name: Apply AI Patch
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  if grep -q "diff --git" ai_fix.patch; then
Â  Â  Â  Â  Â  Â  git apply ai_fix.patch || (echo "Failed to apply patch" && exit 1)
Â  Â  Â  Â  Â  else
Â  Â  Â  Â  Â  Â  echo "No patch found" && exit 1
Â  Â  Â  Â  Â  fi
Â  Â  Â  - name: Commit and Create PR
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  git config user.name "omega-bot"
Â  Â  Â  Â  Â  git config user.email "omega-bot@zeazdev.io"
Â  Â  Â  Â  Â  BRANCH="fix/ai-auto-$(date +%s)"
Â  Â  Â  Â  Â  git checkout -b "$BRANCH"
Â  Â  Â  Â  Â  git add .
Â  Â  Â  Â  Â  git commit -m "ðŸ¤– fix: AI Auto-Fix after CI failure"
Â  Â  Â  Â  Â  git push -u origin "$BRANCH"
Â  Â  Â  Â  Â  gh pr create --title "ðŸ¤– AI Auto-Fix: Repair after CI failure" --body "This PR was automatically generated by the Î©.6 AI Auto-Fix system using GPT-5 analysis."

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
