name: Î©.7 AI Auto-Test Generator
on:
Â  push:
Â  Â  branches: [main, dev, feature/**]
Â  workflow_dispatch:
permissions:
Â  contents: write
Â  pull-requests: write
jobs:
Â  ai-auto-test:
Â  Â  runs-on: ubuntu-latest
Â  Â  steps:
Â  Â  Â  - name: Checkout repository
Â  Â  Â  Â  uses: actions/checkout@v4
Â  Â  Â  - name: Detect dominant language
Â  Â  Â  Â  id: detect
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  if ls *.py >/dev/null 2>&1; then echo "lang=python" >> $GITHUB_OUTPUT
Â  Â  Â  Â  Â  elif ls package.json >/dev/null 2>&1; then echo "lang=javascript" >> $GITHUB_OUTPUT
Â  Â  Â  Â  Â  elif ls *.go >/dev/null 2>&1; then echo "lang=go" >> $GITHUB_OUTPUT
Â  Â  Â  Â  Â  else echo "lang=unknown" >> $GITHUB_OUTPUT
Â  Â  Â  - name: Collect core files
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  mkdir -p source-snippets
Â  Â  Â  Â  Â  find . -type f -name "*.py" -o -name "*.js" -o -name "*.ts" | head -n 10 | xargs -I{} cp {} source-snippets/ || true
Â  Â  Â  Â  Â  tar czf source-snippets.tar.gz source-snippets
Â  Â  Â  - name: Send source to GPT-5 for test generation
Â  Â  Â  Â  env:
Â  Â  Â  Â  Â  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  TEXT=$(base64 source-snippets.tar.gz | head -c 50000)
Â  Â  Â  Â  Â  curl https://api.openai.com/v1/chat/completions \
Â  Â  Â  Â  Â  Â  -H "Authorization: Bearer $OPENAI_API_KEY" \
Â  Â  Â  Â  Â  Â  -H "Content-Type: application/json" \
Â  Â  Â  Â  Â  Â  -d '{
Â  Â  Â  Â  Â  Â  Â  "model": "gpt-5",
Â  Â  Â  Â  _price_tracking_system Â  Â  "messages": [
Â  Â  Â  Â  Â  Â  Â  Â  {"role":"system","content":"You are an expert test engineer. Read the project code and create minimal meaningful unit tests."},
Â  Â  Â  Â  Â  Â  Â  Â  {"role":"user","content":"Base64 archive: '"$TEXT"'"}
Â  Â  Â  Â  Â  Â  Â  ]
Â  Â  Â  Â  Â  Â  }' | jq -r '.choices[0].message.content' > ai_tests.txt
Â  Â  Â  - name: Save generated tests
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  mkdir -p ai_generated_tests
Â  Â  Â  Â  Â  case "${{ steps.detect.outputs.lang }}" in
Â  Â  Â  Â  Â  Â  python) echo "$(<ai_tests.txt)" > ai_generated_tests/test_auto.py ;;
Â  Â  Â  Â  Â  Â  javascript|typescript) echo "$(<ai_tests.txt)" > ai_generated_tests/auto.test.tsx ;;
Â  Â  Â  Â  Â  Â  go) echo "$(<ai_tests.txt)" > ai_generated_tests/auto_test.go ;;
Â  Â  Â  Â  Â  Â  *) echo "$(<ai_tests.txt)" > ai_generated_tests/auto_test.txt ;;
Â  Â  Â  Â  Â  esac
Â  Â  Â  - name: Commit and PR the AI tests
Â  Â  Â  Â  run: |
Â  Â  Â  Â  Â  git config user.name "omega-bot"
Â  Â  Â  Â  Â  git config user.email "omega-bot@zeazdev.io"
Â  Â  Â  Â  Â  BRANCH="test/ai-auto-$(date +%s)"
Â  Â  Â  Â  Â  git checkout -b "$BRANCH"
Â  Â  Â  Â  Â  git add ai_generated_tests/
Â  Â  Â  Â  Â  git commit -m "ðŸ§ª test: add AI-generated tests (Î©.7)"
Â  Â  Â  Â  Â  git push -u origin "$BRANCH"
Â  Â  Â  Â  Â  gh pr create --title "ðŸ§ª AI Auto-Generated Tests (Î©.7)" --body "Automatically generated tests using GPT-5 based on latest project source."
